FROM debian:trixie-20250929-slim AS libslirp-static

ENV DEBIAN_FRONTEND=noninteractive

# https://snapshot.debian.org/archive/debian/20250321T024612Z/
ARG SNAPSHOT=20250930T083630Z

RUN \
  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  : "Enabling snapshot" && \
  sed -i -e '/Types: deb/ a\Snapshot: true' /etc/apt/sources.list.d/debian.sources && \
  : "Enabling cache" && \
  rm -f /etc/apt/apt.conf.d/docker-clean && \
  echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' >/etc/apt/apt.conf.d/keep-cache && \
  : "Fetching the snapshot and installing ca-certificates in one command" && \
  apt install --update --snapshot "${SNAPSHOT}" -o Acquire::Check-Valid-Until=false -o Acquire::https::Verify-Peer=false -y ca-certificates && \
  : "Install dependencies" && \
  apt install --snapshot "${SNAPSHOT}" -y \
  build-essential \
  libglib2.0-dev \
  meson \
  ninja-build \
  pkg-config \
  && \
  : "Clean up for improving reproducibility (optional)" && \
  rm -rf /var/log/* /var/cache/ldconfig/aux-cache

ARG LIBSLIRP_VERSION=v4.9.0
ARG LIBSLIRP_SOURCE=https://gitlab.freedesktop.org/slirp/libslirp/-/archive/${LIBSLIRP_VERSION}/libslirp-${LIBSLIRP_VERSION}.tar.gz
ARG LIBSLIRP_CHKSUM=sha256:e744a32767668fe80e3cb3bd75d10d501f981e98c26a1f318154a97e99cdac22

ADD --checksum=${LIBSLIRP_CHKSUM} ${LIBSLIRP_SOURCE} .

RUN \
  tar -xzf libslirp-${LIBSLIRP_VERSION}.tar.gz && rm -r libslirp-${LIBSLIRP_VERSION}.tar.gz && \
  cd libslirp-${LIBSLIRP_VERSION} && \
  meson setup -Ddefault_library=static build && \
  ninja -Cbuild && \
  mv ./build/libslirp.a /libslirp.a && \
  cd .. && rm -r libslirp-${LIBSLIRP_VERSION}

FROM debian:trixie-20250317-slim

ENV DEBIAN_FRONTEND=noninteractive

# https://snapshot.debian.org/archive/debian/20250321T024612Z/
ARG SNAPSHOT=20250321T024612Z

RUN \
  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  : "Enabling snapshot" && \
  sed -i -e '/Types: deb/ a\Snapshot: true' /etc/apt/sources.list.d/debian.sources && \
  : "Enabling cache" && \
  rm -f /etc/apt/apt.conf.d/docker-clean && \
  echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' >/etc/apt/apt.conf.d/keep-cache && \
  : "Fetching the snapshot and installing ca-certificates in one command" && \
  apt install --update --snapshot "${SNAPSHOT}" -o Acquire::Check-Valid-Until=false -o Acquire::https::Verify-Peer=false -y ca-certificates && \
  : "Install dependencies" && \
  apt install --snapshot "${SNAPSHOT}" -y \
  build-essential \
  checkinstall \
  git \
  libglib2.0-dev \
  libpixman-1-dev \
  libslirp-dev \
  ninja-build \
  pkg-config \
  python3-venv \
  && \
  : "Clean up for improving reproducibility (optional)" && \
  rm -rf /var/log/* /var/cache/ldconfig/aux-cache

COPY --from=libslirp-static libslirp.a .

ARG LIBSLIRP_CHKSUM=efd9d0c98ca05da3a8ea64ad0e7701bd8f447b81816c45939a33b8a676c2ccb4

RUN \
  shasum -a 256 libslirp.a && echo "${LIBSLIRP_CHKSUM}  libslirp.a" | shasum -c && \
  mv libslirp.a /lib/x86_64-linux-gnu/
