FROM debian:trixie-20260112-slim AS libslirp-static

ENV DEBIAN_FRONTEND=noninteractive

# https://snapshot.debian.org/archive/debian/20260112T000000Z/
ARG SNAPSHOT=20260112T000000Z

RUN \
  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  : "Enabling snapshot" && \
  sed -i -e '/Types: deb/ a\Snapshot: true' /etc/apt/sources.list.d/debian.sources && \
  : "Enabling cache" && \
  rm -f /etc/apt/apt.conf.d/docker-clean && \
  echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' >/etc/apt/apt.conf.d/keep-cache && \
  : "Fetching the snapshot and installing ca-certificates in one command" && \
  apt install --update --snapshot "${SNAPSHOT}" -o Acquire::Check-Valid-Until=false -o Acquire::https::Verify-Peer=false -y ca-certificates && \
  : "Install dependencies" && \
  apt install --snapshot "${SNAPSHOT}" -y \
  build-essential \
  libglib2.0-dev \
  meson \
  ninja-build \
  pkg-config \
  && \
  : "Clean up for improving reproducibility (optional)" && \
  rm -rf /var/log/* /var/cache/ldconfig/aux-cache

ARG LIBSLIRP_VERSION=v4.9.1
ARG LIBSLIRP_SOURCE=https://gitlab.freedesktop.org/slirp/libslirp/-/archive/${LIBSLIRP_VERSION}/libslirp-${LIBSLIRP_VERSION}.tar.gz
ARG LIBSLIRP_CHKSUM=sha256:3970542143b7c11e6a09a4d2b50f30a133473c41f15ed0bdcc3b7a1c450d9a5c

ADD --checksum=${LIBSLIRP_CHKSUM} ${LIBSLIRP_SOURCE} .

RUN \
  tar -xzf libslirp-${LIBSLIRP_VERSION}.tar.gz && rm -r libslirp-${LIBSLIRP_VERSION}.tar.gz && \
  cd libslirp-${LIBSLIRP_VERSION} && \
  meson setup -Ddefault_library=static build && \
  ninja -Cbuild && \
  mv ./build/libslirp.a /libslirp.a && \
  cd .. && rm -r libslirp-${LIBSLIRP_VERSION}

FROM debian:trixie-20260112-slim

ENV DEBIAN_FRONTEND=noninteractive

# https://snapshot.debian.org/archive/debian/20260112T000000Z/
ARG SNAPSHOT=20260112T000000Z

RUN \
  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  : "Enabling snapshot" && \
  sed -i -e '/Types: deb/ a\Snapshot: true' /etc/apt/sources.list.d/debian.sources && \
  : "Enabling cache" && \
  rm -f /etc/apt/apt.conf.d/docker-clean && \
  echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' >/etc/apt/apt.conf.d/keep-cache && \
  : "Fetching the snapshot and installing ca-certificates in one command" && \
  apt install --update --snapshot "${SNAPSHOT}" -o Acquire::Check-Valid-Until=false -o Acquire::https::Verify-Peer=false -y ca-certificates && \
  : "Install dependencies" && \
  apt install --snapshot "${SNAPSHOT}" -y \
  build-essential \
  checkinstall \
  git \
  libglib2.0-dev \
  libpixman-1-dev \
  libslirp-dev \
  ninja-build \
  pkg-config \
  python3-venv \
  && \
  : "Clean up for improving reproducibility (optional)" && \
  rm -rf /var/log/* /var/cache/ldconfig/aux-cache

COPY --from=libslirp-static libslirp.a .

ARG LIBSLIRP_CHKSUM=0fe41c23b77bb2c59b4e6c965591b01103cb4763c85f751993b02447a4da6dc4

RUN \
  shasum -a 256 libslirp.a && echo "${LIBSLIRP_CHKSUM}  libslirp.a" | shasum -c && \
  mv libslirp.a /lib/x86_64-linux-gnu/
