name: linux-kernel

on:
  push:
    branches:
      - linux-kernel

env:
  builder: builder-1
  ref: ref-1

jobs:
  linux-kernel:
    runs-on: ubuntu-latest
    steps:
      - run: echo "kernel ${{ env.builder }} - ${{ env.ref }}" > linux-kernel.txt

      - name: Publish kernel
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          files: |
            ${{ github.workspace }}/linux-kernel.txt
