name: ovmf

on:
  push:
    branches:
      - ovmf

env:
  builder: builder-2
  ref: ref-2

jobs:
  ovmf:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ovmf ${{ env.builder }} - ${{ env.ref }}" > ovmf.txt

      - name: Publish OVMF
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          files: |
            ${{ github.workspace }}/ovmf.txt
